### ISSUE TITLE
Release 1.5.2

### ISSUE THREAD

**Issue by aairey** [transferwise/pipelinewise-tap-mysql#121]
@Samira-El  Can we release 1.5.2 with the current changes?
* mysql-replication update to 0.30

We are facing an issue with encoded characters which is breaking the pipelinewise run and this might solve it.

PS: if you want we can create the PR for the version bump, but it needs to get approved as well. Not sure if you need more maintainers as movement is slow in this project.

**Comment by Samira-El** [comment]
Hi @aairey,

Please do create a PR, I can approve it.

**Comment by aairey** [comment]
@Samira-El Thanks, see PR#122.
