### ISSUE TITLE
Broken dependencies with pipelinewise-singer-python

### ISSUE THREAD

**Issue by jmriego** [transferwise/pipelinewise-tap-mysql#22]
Hi! I'm not sure if I'm making a mistake, but I can't seem to be able to build the Pipelinewise Docker image.

While installing the tap MySQL it's failing with this error:
`ERROR: jsonschema 3.2.0 has requirement attrs>=17.4.0, but you'll have attrs 16.3.0 which is incompatible.`

As far as I can see, the dependency conflict is between this tap requiring `attrs 16.3.0` and the `pipelinewise-singer-python` requiring `jsonschema==3.2.0` which itself depends on `attrs>=17.4.0`

Thanks in advance!

**Comment by koszti** [comment]
this is introduced by a jsonschema upgrade in the upstream singer-python package at https://github.com/transferwise/pipelinewise-singer-python/commit/881a7384280cfd4b8e88dbc17a4ca0e7bc58cfbe

Fix is work in progress..

**Comment by koszti** [comment]
this has been fixed and pipelinewise-tap-mysql 1.3.2 and updated in main PPW master
