### ISSUE TITLE
bit(1) values converted to true

### ISSUE THREAD

**Issue by ile-g** [transferwise/pipelinewise-tap-mysql#37]
**Tap version**: 1.3.7
**Mysql version**: 5.7

When getting data from a `bit(1)` column, the value `b'0'` is mapped to `true` instead of `false`. The column is seen as a boolean but the value is not mapped correctly.
Adding the extra check  `or elem == b'\x00'` in the mapping logic might do the trick:
https://github.com/transferwise/pipelinewise-tap-mysql/blob/7df974e832122a8110eb3ef894f069a396717f70/tap_mysql/sync_strategies/common.py#L111

**Comment by koszti** [comment]
released to PyPI as [pipelinewise-tap-mysql-1.3.8](https://pypi.org/project/pipelinewise-tap-mysql/)
