### ISSUE TITLE
Endless Loop? "Running discovery"

### ISSUE THREAD

**Issue by kg6zgj** [transferwise/pipelinewise-tap-mysql#39]
is this log firing constantly indicative of an endless loop? time=2020-10-06 19:18:19 logger_name=tap_mysql log_level=INFO message=Running discovery ...

**Comment by Samira-El** [comment]
Hey Daniel, 

**Short answer**
No, it's not an endless loop, this is normal but not ideal.

**Long answer**
The _Log based_ replication method is designed to be detect changes in the source table structure by comparing the columns in the log message to the schema it has in memory, if there are new column that it doesn't recognize, it runs discovery then publishes a new Singer schema message to stdout.

There are edge cases where the table has a column of unsupported type, which during discovery is ignored and not added to the table's json schema representation, thus, when processing a binlog message, it detects that a column is not in the schema and reruns discovery.

This is normal but could definitely be improved, I'll raise a ticket and work on this when I have time.

**Comment by kg6zgj** [comment]
I think it is safe to say that this is a bug. 
my properties file just keeps growing and the there is no data being synced.
![image](https://user-images.githubusercontent.com/3739899/96644359-95392a00-12ee-11eb-9b37-230139376aea.png)

**Comment by kg6zgj** [comment]
I will see If I can improve this process and open a PR

**Comment by Samira-El** [comment]
Thanks,
A PR would be really appreciated, let me know if you need any help.
